### ISSUE TITLE
No Documentation for Search Hash in Iris Investigate

### ISSUE THREAD

**Issue by piffey** [DomainTools/python_api#46]
The search_hash parameter in Iris Investigate is super useful for monitoring an investigation -- particularly when paired with the results_updated_after parameter. This is a note both for myself -- or whoever gets around to it -- to add that documentation for future reference.

**Comment by tlansec** [comment]
For anyone reading this now note that the "results_updated_after" parameter is named "data_updated_after" and is not as useful as it seems as it only reflects when the record was last updated - and since records are constantly being updated this means it cannot be used to filter for new results for a given query.
